services:
  web:
    image: oven/bun:1.1-alpine
    working_dir: /repo
    ports:
      - "3000:3000"
    volumes:
      - .:/repo
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
    command: turbo run dev --filter=web -- --port 3000 --hostname 0.0.0.0
